name: Android E2E Tests

on:
  push:

jobs:
  build:
    timeout-minutes: 90
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        api-level: [ 27, 28]
        arch: [x86, x86_64]
        target: [default]
        include:
          - api-level: 26
            target: google_apis
            arch: x86

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log environment info
        run: npx envinfo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build Android App
        run: |
          yarn expo prebuild --platform android
          cd android
          ./gradlew assembleRelease

      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          cores: 2
          ram-size: 2048M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            adb devices
            adb install android/app/build/outputs/apk/release/app-release.apk
            maestro test .maestro/

      - name: Upload Maestro artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-artifacts
          path: |
            ~/.maestro/tests/
            /home/runner/.maestro/tests/
            /home/runner/.maestro/logs/
