name: Android Build & Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    env:
      JAVA_OPTS: "-Xmx4g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx4g"
      NODE_OPTIONS: "--max_old_space_size=4096"
      ANDROID_EMULATOR_USE_SYSTEM_LIBS: "1"
      ANDROID_EMU_GO_FASTER: "1"

    steps:
    - uses: actions/checkout@v3

    - name: Configure system resources
      run: |
        # File system and memory settings
        echo "fs.inotify.max_user_watches=524288" | sudo tee -a /etc/sysctl.conf
        echo "vm.swappiness=0" | sudo tee -a /etc/sysctl.conf
        echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf
        echo "vm.overcommit_memory=1" | sudo tee -a /etc/sysctl.conf
        
        # Apply all settings
        sudo sysctl -p
        
        # Disable unnecessary services
        sudo service mysql stop || true
        sudo service postgresql stop || true
        sudo service redis-server stop || true
        sudo service docker stop || true
        
        # Verify settings
        sysctl vm.swappiness
        sysctl fs.inotify.max_user_watches
        sysctl vm.max_map_count

    - name: Setup KVM with enhanced permissions
      run: |
        echo "Installing and configuring KVM"
        sudo apt-get update
        sudo apt-get --quiet install --yes \
          qemu-kvm \
          libvirt-daemon-system \
          libvirt-clients \
          bridge-utils \
          cpu-checker
        
        sudo adduser $USER kvm
        sudo adduser $USER libvirt
        sudo chown root:kvm /dev/kvm
        sudo chmod 660 /dev/kvm
        
        # Verify KVM installation
        kvm-ok || exit 1
        virsh list --all

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Cache Android SDK
      uses: actions/cache@v3
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-cache-${{ runner.os }}-${{ hashFiles('**/build.gradle') }}

    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
        curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Setup Android SDK and Emulator
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libpulse0 \
          libgl1 \
          libxcursor1 \
          libxdamage1 \
          libxrandr2 \
          libasound2 \
          libgtk-3-0 \
          libglu1-mesa

        sdkmanager --install \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.0" \
          "system-images;android-33;google_apis;x86_64" \
          "emulator"

    - name: Run Android tests
      env:
        CI: true
        QEMU_AUDIO_DRV: "none"
        QEMU_CPU_COUNT: "2"
        QEMU_RAM_SIZE: "4096"
        ANDROID_EMULATOR_USE_SYSTEM_LIBS: "1"
      run: bash ./tests/test-android.sh

    - name: Upload test artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        path: |
          test-artifacts/
          logs/
        retention-days: 3
