name: Android E2E Tests

on:
  push:

jobs:
  build:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        api-level: [28, 31, 33]
        arch: [x86_64]
        target: [default, google_apis]
        include:
          - api-level: 26
            target: google_apis
            arch: x86
          - api-level: 28
            target: default
            arch: x86_64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log environment info
        run: npx envinfo

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Build Android App
        run: |
          yarn generate-test-data
          yarn expo prebuild --platform android
          cd android
          ./gradlew assembleRelease

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Android Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          cores: 4
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: true
          script: |
            adb devices
            adb install android/app/build/outputs/apk/release/app-release.apk
            maestro test .maestro/

      - name: Upload Maestro artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-artifacts-api${{ matrix.api-level }}-${{ matrix.target }}-${{ matrix.arch }}
          path: |
            ~/.maestro/tests/
            /home/runner/.maestro/tests/
            /home/runner/.maestro/logs/
