name: iOS Build and Render Test

on:
  push:

jobs:
  build:
    # TODO: Re-enable once there are more run minutes available
    if: false 
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Install Maestro
        run: |
          curl -Ls "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> $GITHUB_PATH

      - name: Run iOS Build and Tests
        env:
          # According to the official GH Runner images repo, this simulator is available on this runner
          SIMULATOR_DEVICE: "iPhone 15"
        run: bash tests/test-ios.sh
